name: Sync Upstream
on: 
  schedule:
    - cron: '0 5 * * *'
jobs:
  sync: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          alias git="time git"

          git config --global user.name 'Tsiry Marcel'
          git config --global user.email 'f3lin-mntm@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/disposable/disposable-email-domains.git
          git fetch upstream

          git checkout master
          git rebase --quiet upstream/master
          git push --force origin master
